os: Visual Studio 2019

platform: x64

branches:
  # whitelist
  only:
#    - main
    - someBranch

install:
#  - set PATH=C:\msys64\usr\bin;%PATH%
  - mkdir C:\__software
  - cd C:\__software
 
  - curl https://rakudo.org/dl/rakudo/rakudo-moar-2022.07-01-win-x86_64-msvc.msi -o C:\__software\rakudo-moar.msi
  - msiexec /i C:\__software\rakudo-moar.msi

  - git clone https://github.com/ugexe/zef.git
  - cd zef
  - raku -I. bin/zef install .
#  - zef --verbose --force install Zef


build: off

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - zef --depsonly install .
  - prove -v -e "raku -Ilib" t/

# fetch repository as zip archive
#shallow_clone: true

# set clone depth
#clone_depth: 4
