os: Visual Studio 2019

platform: x64

branches:
  # whitelist
  only:
    - master
    - raku-rename

install:
  - set PATH=C:\msys64\usr\bin;%PATH%
#  - bash -lc "pacman -S --noconfirm mingw-w64-x86_64-toolchain"
  - bash -lc "pacman -S --noconfirm mingw-w64-x86_64-toolchain base-devel"
#  - bash -lc "pacman -S --noconfirm mingw-w64-x86_64-gtk3"
#  - cmd: dir C:\program files
#  - cmd: dir C:\windows

#  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
#  - choco feature enable -n allowEmptyChecksums
#  - choco install strawberryperl
#  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - git clone https://github.com/rakudo/rakudo.git %APPVEYOR_BUILD_FOLDER%\..\rakudo
  - cd %APPVEYOR_BUILD_FOLDER%\..\rakudo
  - perl Configure.pl --gen-moar=HEAD --gen-nqp
  - nmake install
  - SET PATH=%APPVEYOR_BUILD_FOLDER%\..\rakudo\install\bin;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%


  - git clone https://github.com/ugexe/zef.git %APPVEYOR_BUILD_FOLDER%\..\zef
  - cd %APPVEYOR_BUILD_FOLDER%\..\zef
  - perl6 -Ilib bin/zef --verbose install .
#  - zef --verbose --force install Zef


build: off

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - zef --depsonly install .
  - prove -v -e "perl6 -Ilib" t/

# fetch repository as zip archive
shallow_clone: true

# set clone depth
clone_depth: 4
